plugins {
    id 'com.android.application'
}

android {
    namespace 'com.spectra.analyzer'
    compileSdk 35

    defaultConfig {
        applicationId 'com.spectra.analyzer'
        minSdk 26
        targetSdk 35
        versionCode 11
        versionName '1.1.0'
        testInstrumentationRunner 'com.spectra.analyzer.ModelTests'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
